export const revenueExpensesData = [
  { month: "January", revenue: 14000, expenses: 10000 },
  { month: "February", revenue: 16000, expenses: 12000 },
  { month: "March", revenue: 6000, expenses: 22000 },
  { month: "April", revenue: 15000, expenses: 6000 },
  { month: "May", revenue: 12000, expenses: 11000 },
  { month: "June", revenue: 16000, expenses: 14000 },
  { month: "July", revenue: 21000, expenses: 10000 },
];

export const profitTrendData = [
  { month: "Jan", profit: 50000 },
  { month: "Feb", profit: 47000 },
  { month: "Mar", profit: 52000 },
  { month: "Apr", profit: 44000 },
  { month: "May", profit: 46000 },
  { month: "Jun", profit: 43000 },
  { month: "Jul", profit: 38000 },
  { month: "Aug", profit: 36000 },
  { month: "Sep", profit: 40000 },
  { month: "Oct", profit: 45000 },
  { month: "Nov", profit: 52000 },
  { month: "Dec", profit: 58000 },
];

export const expenseBreakdown = [
  { name: "Payrolls", value: 70, amount: 2000, color: "#4ade80" },
  { name: "Tools", value: 20, amount: 1000, color: "#f87171" },
  { name: "Subscription", value: 10, amount: 500, color: "#60a5fa" },
];

export const statsCards = [
  {
    icon: "$",
    title: "Total revenue",
    value: "$32,000",
    change: "+12%",
    trend: "up" as const,
    subtext: "Up 5% compared to last month",
  },
  {
    icon: "$",
    title: "Total expenses",
    value: "$32,000",
    change: "-5%",
    trend: "down" as const,
    subtext: "Down 5% compared to last month",
  },
  {
    icon: "$",
    title: "Total expenses",
    value: "$32,000",
    change: "-5%",
    trend: "down" as const,
    subtext: "Down 5% compared to last month",
  },
  {
    icon: "$",
    title: "Burn rate",
    value: "$32,000",
    change: "-5%",
    trend: "down" as const,
    subtext: "Down 5% compared to last month",
  },
];

export const transactionsData = [
  {
    id: 1,
    date: "Feb 23, 2025",
    type: "Income",
    category: "Client payment",
    description: "Invoice #128",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 2,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Tool",
    description: "Figma Pro Subscription",
    amount: "-$4,900",
    method: "Card",
    status: "Paid",
  },
  {
    id: 3,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 4,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 5,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 6,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 7,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 8,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 9,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
  {
    id: 10,
    date: "Feb 23, 2025",
    type: "Expenses",
    category: "Client payment",
    description: "Client payment",
    amount: "+$4,900",
    method: "Stripe",
    status: "Received",
  },
];
